### ISSUE TITLE
Will there be model weights?

### ISSUE THREAD

**Issue by zaccharieramzi** [polo5/LDEQ_RwR#1]
Hi,

I have just read briefly your paper, and I found the idea to be super well thought, and a nice improvement over the previous reuse idea of Bai et al. in their optical flow work.
I am really interested in the code to be able to play around with the model you trained on the WFLW (i.e. non-video) dataset.

Do you think it might be possible to include model weights in the release? That would be amazing for me.

**Comment by polo5** [comment]
Hi @zaccharieramzi, thanks for your interest!

I've been pushing Nvidia to give me the authorization to opensource all of our work, but they have been very slow sadly. The initial plan was to release trained weights + evaluation code (but not the training code). Will let you know if I have updates from them, hopefully soon.

Best,
Paul

**Comment by zaccharieramzi** [comment]
If I can have just the weights + the evaluation script like before mid-May  it would make me really happy! I would be able to include this evaluation in my review

Congratulations on the work anyway,
Cheers

**Comment by polo5** [comment]
Released. Closing
