### ISSUE TITLE
landmarks visualization

### ISSUE THREAD

**Issue by bboogi** [polo5/LDEQ_RwR#3]
I read your paper with great interest!

I want to **visualize the landmark** extracted while running the code, can you help me with that?

Thank you.

**Comment by polo5** [comment]
Hi @bboogi. Sorry for the late reply. 

Though I didn't release my own video visualization code, you can use the code [in this file](https://github.com/polo5/LDEQ_RwR/blob/main/datasets/WFLW/dataset.py) which visualizes kpts on images as inspiration. 

Hope this helps
